{
 "title": "VictoriaMetrics Cluster Per Tenant Statistic (VM)",
 "description": "Overview for enterprise cluster VictoriaMetrics v1.56.0 or higher",
 "tags": [
  "VictoriaMetrics",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "victoriametrics-datasource" },
   {
    "name": "account",
    "query": {
     "query": "label_values(vm_tenant_active_timeseries, accountID)"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "label_values(vm_tenant_active_timeseries{accountID=~\"$accountID\"},projectID)"
    }
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  { "title": "Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datapoints ingestion rate",
   "type": "timeseries",
   "description": "How many datapoints are inserted into storage per second by accountID and projectID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_tenant_inserted_rows_total{accountID=~\"$account\", projectID=~\"$project\"}[$__rate_interval])) by (accountID,projectID) ",
     "legendFormat": "{{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Read query rate",
   "type": "timeseries",
   "description": "Request rate accepted by vmselect nodes per tenant",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_tenant_select_requests_total{accountID=~\"$account\", projectID=~\"$project\"}[$__rate_interval])) by (accountID,projectID) ",
     "legendFormat": "{{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Active time series",
   "type": "timeseries",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tenant_active_timeseries{accountID=~\"$account\",projectID=~\"$project\"}) by(accountID,projectID)",
     "legendFormat": "{{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Time spent on queries, seconds",
   "type": "timeseries",
   "description": "Time spent on query execution per tenant per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_tenant_select_requests_duration_ms_total{accountID=~\"$account\", projectID=~\"$project\"}[$__rate_interval])) by (accountID,projectID) /1000",
     "legendFormat": "{{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "Disk space usage (datapoints only) ",
   "type": "timeseries",
   "description": "Shows the amount of on-disk space occupied by data points only. The disk space is used for storing by datapoint and indexdb. There is no option to expose per tenant statistic for indexdb. Usually, indexed takes much less space compared to datapoints. But with a high churn rate, the size of the indexdb could grow significantly.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vm_tenant_used_tenant_bytes{accountID=~\"$account\",projectID=~\"$project\"}) by(accountID, projectID)",
     "legendFormat": "{{accountID}}:{{projectID}}"
    }
   ]
  },
  {
   "title": "New series over 24h ",
   "type": "timeseries",
   "description": "Number of new series created over last 24h.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vm_tenant_timeseries_created_total{accountID=~\"$account\", projectID=~\"$project\"}[24h])) by(accountID,projectID)",
     "legendFormat": "{{accountID}}:{{projectID}}"
    }
   ]
  },
  { "title": "Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Ingestion Rate Top 5, by account id ",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_last(5, sum(rate(vm_tenant_inserted_rows_total{accountID=~\"$account\"}[$__range])) by (accountID), \"accountID=other\") ",
     "legendFormat": "{{accountID}}"
    }
   ]
  },
  {
   "title": "Read query rate, Top 5, by account id",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_last(5, sum(rate(vm_tenant_select_requests_total{accountID=~\"$account\"}[$__rate_interval])) by (accountID), \"accountID=other\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent on queries, seconds, Top 5, by account id",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_last(5, sum(rate(vm_tenant_select_requests_duration_ms_total{accountID=~\"$account\"}[$__range])) by (accountID) /1000, \"accountID=other\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active time series, Top 5, by account id ",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_last(5, sum(vm_tenant_active_timeseries{accountID=~\"$account\"}) by(accountID), \"accountID=other\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space usage, Top 5, by account id ",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_last(5, sum(vm_tenant_used_tenant_bytes{accountID=~\"$account\"}) by(accountID), \"accountID=other\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New series over 24h, Top 5, by account id ",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_last(5, sum(increase(vm_tenant_timeseries_created_total{accountID=~\"$account\"}[24h])) by(accountID), \"accountID=other\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Rate, Top 5, by account id",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk_last(5, sum(rate(vm_tenant_inserted_rows_total{accountID=~\"$account\"}[$__range])) by (accountID), \"accountID=other\") ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Read query rate, Top 5, by account id",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk_last(5, sum(rate(vm_tenant_select_requests_total{accountID=~\"$account\"}[$__rate_interval])) by (accountID), \"accountID=other\") ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Time spent on queries, seconds, Top 5, by account id",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk_last(5, sum(rate(vm_tenant_select_requests_duration_ms_total{accountID=~\"$account\"}[$__range])) by (accountID) /1000, \"accountID=other\") ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Active time series, Top 5, by account id",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk_last(5, sum(vm_tenant_active_timeseries{accountID=~\"$account\"}) by(accountID), \"accountID=other\") ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk space usage, Top 5, by account id",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk_last(5, sum(vm_tenant_used_tenant_bytes{accountID=~\"$account\"}) by(accountID), \"accountID=other\") ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "New series over 24h, Top 5, by account id",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk_last(5, sum(increase(vm_tenant_timeseries_created_total{accountID=~\"$account\"}[24h])) by(accountID), \"accountID=other\") ",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}