services:
  #  Metrics collector.
  #  It scrapes targets defined in --promscrape.config
  #  And forward them to --remoteWrite.url
  vmagent-1:
    container_name: vmagent-1
    image: zeyingz/vmagent-insert-throughput:v0.0.3
    deploy:
      placement:
        constraints: 
          - node.labels.role == datasource
    depends_on:
      - "vminsert-1"
      - "vminsert-2"
    ports:
      - 8429
    volumes:
      - vmagentdata-1:/vmagentdata
      - ./prometheus-cluster-vmagent-1.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://vminsert-1:8480/insert/0/prometheus/"
      - "--remoteWrite.url=http://vminsert-2:8480/insert/0/prometheus/"
      - "--testSampleLength=2160000"
      - "--testTimeseriesNum=10000"
      - "--testStartSeriesID=0"
      - "--testInsertNodeNum=2"
    restart: always
  vmagent-2:
    container_name: vmagent-2
    image: zeyingz/vmagent-insert-throughput:v0.0.3
    deploy:
      placement:
        constraints: 
          - node.labels.role == worker3
    depends_on:
      - "vminsert-1"
      - "vminsert-2"
    ports:
      - 8429
    volumes:
      - vmagentdata-2:/vmagentdata
      - ./prometheus-cluster-vmagent-2.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://vminsert-1:8480/insert/0/prometheus/"
      - "--remoteWrite.url=http://vminsert-2:8480/insert/0/prometheus/"
      - "--testSampleLength=2160000"
      - "--testTimeseriesNum=10000"
      - "--testStartSeriesID=10000"
      - "--testInsertNodeNum=2"
    restart: always

  # vmstorage shards. Each shard receives 1/N of all metrics sent to vminserts,
  # where N is number of vmstorages (2 in this case).
  vmstorage-1:
    container_name: vmstorage-1
    image: victoriametrics/vmstorage:v1.108.1-cluster 
    deploy:
      placement:
        constraints: 
          - node.labels.role == datasource
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-1:/storage
    command:
      - "--storageDataPath=/storage"
    restart: always
  vmstorage-2:
    container_name: vmstorage-2
    image: victoriametrics/vmstorage:v1.108.1-cluster 
    deploy:
      placement:
        constraints: 
          - node.labels.role == worker
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-2:/storage
    command:
      - "--storageDataPath=/storage"
    restart: always
  # vmstorage shards. Each shard receives 1/N of all metrics sent to vminserts,
  # where N is number of vmstorages (2 in this case).
  vmstorage-3:
    container_name: vmstorage-3
    image: victoriametrics/vmstorage:v1.108.1-cluster 
    deploy:
      placement:
        constraints: 
          - node.labels.role == datasource
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-3:/storage
    command:
      - "--storageDataPath=/storage"
    restart: always
  vmstorage-4:
    container_name: vmstorage-4
    image: victoriametrics/vmstorage:v1.108.1-cluster 
    deploy:
      placement:
        constraints: 
          - node.labels.role == worker
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-4:/storage
    command:
      - "--storageDataPath=/storage"
    restart: always

  # vmsketch shards. Each shard receives 1/N of all metrics sent to vminserts,
  # where N is number of vmsketches (2 in this case).
  vmsketch-1:
    container_name: vmsketch-1
    image: zeyingz/vmsketch-insert-throughput:v0.0.2
    deploy:
      placement:
        constraints: 
          - node.labels.role == datasource
    ports:
      - 8582
      - 8500
      - 8501
    command:
      - "--testWindowSize=1000000"
      - "--testAlgo=ehuniv"
    restart: always
  vmsketch-2:
    container_name: vmsketch-2
    image: zeyingz/vmsketch-insert-throughput:v0.0.2
    deploy:
      placement:
        constraints: 
          - node.labels.role == worker
    ports:
      - 8582
      - 8500
      - 8501
    command:
      - "--testWindowSize=1000000"
      - "--testAlgo=ehuniv"
    restart: always
  vmsketch-3:
    container_name: vmsketch-3
    image: zeyingz/vmsketch-insert-throughput:v0.0.2
    deploy:
      placement:
        constraints: 
          - node.labels.role == datasource
    ports:
      - 8582
      - 8500
      - 8501
    command:
      - "--testWindowSize=1000000"
      - "--testAlgo=ehuniv"
    restart: always
  vmsketch-4:
    container_name: vmsketch-4
    image: zeyingz/vmsketch-insert-throughput:v0.0.2
    deploy:
      placement:
        constraints: 
          - node.labels.role == worker
    ports:
      - 8582
      - 8500
      - 8501
    command:
      - "--testWindowSize=1000000"
      - "--testAlgo=ehuniv"
    restart: always

  # vminsert is ingestion frontend. It receives metrics pushed by vmagent,
  # pre-process them and distributes across configured vmstorage shards.
  vminsert-1:
    container_name: vminsert-1
    image: zeyingz/vminsert-insert-throughput:v0.0.1
    deploy:
      placement:
        constraints: 
          - node.labels.role == datasource
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
      - "vmstorage-3"
      - "vmstorage-4"
      - "vmsketch-1"
      - "vmsketch-2"
      - "vmsketch-3"
      - "vmsketch-4"
    command:
      - "--storageNode=vmstorage-1:8400"
      - "--storageNode=vmstorage-2:8400"
      - "--storageNode=vmstorage-3:8400"
      - "--storageNode=vmstorage-4:8400"
      - "--sketchNode=vmsketch-1:8500"
      - "--sketchNode=vmsketch-2:8500"
      - "--sketchNode=vmsketch-3:8500"
      - "--sketchNode=vmsketch-4:8500"
    ports:
      - 8480
    restart: always
  vminsert-2:
    container_name: vminsert-2
    image: zeyingz/vminsert-insert-throughput:v0.0.1
    deploy:
      placement:
        constraints: 
          - node.labels.role == worker3
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
      - "vmstorage-3"
      - "vmstorage-4"
      - "vmsketch-1"
      - "vmsketch-2"
      - "vmsketch-3"
      - "vmsketch-4"
    command:
      - "--storageNode=vmstorage-1:8400"
      - "--storageNode=vmstorage-2:8400"
      - "--storageNode=vmstorage-3:8400"
      - "--storageNode=vmstorage-4:8400"
      - "--sketchNode=vmsketch-1:8500"
      - "--sketchNode=vmsketch-2:8500"
      - "--sketchNode=vmsketch-3:8500"
      - "--sketchNode=vmsketch-4:8500"
    ports:
      - 8480
    restart: always
 
volumes:
  vmagentdata-1: {}
  vmagentdata-2: {}
  strgdata-1: {}
  strgdata-2: {}
  strgdata-3: {}
  strgdata-4: {}
  
